### PR TITLE
Simplify templates

### PR DESCRIPTION
**Pull request by FinalAngel**
The goal of this Pull Request is:

- Simplify template structure
- Remove unnecessary placeholder and blocks
- In general make everything simple for easier explanation

We also want to remove ``render_placeholder view.config`` and later only mention it in the documentation (separate PR will follow).

### CODE REVIEW

**Comment by vxsx** [comment]
Codewise it looks good to me, although i wouldn't say that the placeholders you remove were "unused"

**Comment by FinalAngel** [comment]
@vxsx they have been removed on the standardsite and will be on divio and django-cms.org

**Comment by vxsx** [comment]
sure sure, just saying, it's still an open source project and this is a breaking change

**Comment by vxsx** [comment]
well, :+1:

**Comment by lory87** [comment]
lgtm

**Pull request merged**
