### PR TITLE
Force the process to exit with error code if couldn't create the tunnel

### PR DESCRIPTION
**Pull request by Marketionist**
**This pull request updates _gulpfile.js_ to force the process to exit with error code if couldn't create the Sauce Labs tunnel**

### CODE REVIEW

**Comment by Marketionist** [comment]
Please review and merge if ok @FinalAngel @vxsx

**Comment by FinalAngel** [comment]
didn't we remove that once on purpose @vxsx ?

**Comment by vxsx** [comment]
not really @FinalAngel 
i don't mind this to be in, i think other essential addons have it

**Comment by Marketionist** [comment]
@FinalAngel @vxsx please merge if it's ok

**Comment by vxsx** [comment]
@Marketionist could you rebase on top of latest master?

**Comment by FinalAngel** [comment]
:+1:

**Comment by Marketionist** [comment]
Updated to recent master, @FinalAngel @vxsx please merge

**Comment by FinalAngel** [comment]
thank you @Marketionist

**Comment by Marketionist** [comment]
Yes, the tests are failing due to "Failed to create Sauce tunnel" and I can't retrigger the Travis CI build (don't have rights). Maybe you could do it @FinalAngel @vxsx ?

**Comment by Marketionist** [comment]
Also as I see from the logs some environment variables are not being set:
```
Setting environment variables from .travis.yml
$ export TOXENV=py27-dj17-sqlite-cms32-fe
```
instead of:
```
Setting environment variables from .travis.yml
$ export SAUCE_USERNAME=[secure]
$ export SAUCE_ACCESS_KEY=[secure]
$ export CODECLIMATE_REPO_TOKEN=[secure]
$ export TOXENV=py27-dj17-sqlite-cms32-fe
```

Maybe it's related to the rights restrictions?

**Comment by FinalAngel** [comment]
@Marketionist I gladly re-trigger the tests, but we cannot merge as long as they are failing.

**Comment by Marketionist** [comment]
@FinalAngel @vxsx I believe the tests are failing due to rights restrictions of committer (secure environment variables are not being set). But if the committer is a person with full access to repository, then secure environment variables are being set properly. See the same example for aldryn-events - failing build from my commit (with restricted rights) - [https://travis-ci.org/aldryn/aldryn-events/jobs/96612669#L168](https://travis-ci.org/aldryn/aldryn-events/jobs/96612669#L168); Green build from the next pull request by Kirill (with proper rights) - [https://travis-ci.org/aldryn/aldryn-events/jobs/98685780#L161](https://travis-ci.org/aldryn/aldryn-events/jobs/98685780#L161)

**Pull request merged**
